algo_params:
  batch_size: 50
  learning_rate: 0.0001
  n_steps: 200
  num_timesteps: 1000000
  policy: MlpPolicy
  policy_kwargs:
    activation_fn: tanh
    pi: 256
    qf: 256
  policy_type: off_policy
  special_callback: DMbicCallback
  total_timesteps: 1000000.0
  train_freq: 1
algorithm: sac
env_params:
  env_name: alr_envs:DeepMindBallInCupDense-v1
  num_envs: 1
  wrapper: VecNormalize
eval_env:
  eval_freq: 500
  n_eval_episode: 10
name: DeepMind_Ball_In_Cup + SAC
path: logs/sac/DeepMindBallInCupDense-v1_4
path_in: logs/sac/DeepMindBallInCupDense-v1_4/SAC_1
path_out: logs/sac/DeepMindBallInCupDense-v1_4/data.csv
seed: 15
