---
# Slurm config
name: "SLURM"
partition: "dev"
account: ""  # important for HHLR cluster
job-name: "cma"  # this will be the experiment's name in slurm
#experiment_copy_dst: "/home/max_li/exp_code"
#path_to_template: "/home/max_li/code/cw2/cma_tutorial/sbatch_template.sh"  # TODO: get absolute path from current pwd or so
path_to_template: "/media/gyh/sdb5/home/software/MasterThesis/src/cw2/cma_tutorial/sbatch_template.sh"
num_parallel_jobs: 120
ntasks: 1
cpus-per-task: 1
mem-per-cpu: 1000
time: 30

---
# DEFAULT
name: "DEFAULT"
repetitions: 1 # number of times one set of parameters is run
iterations: 100  # number of iterations per repetition
path: "cmaes"
gui: false
params:
  stop_at_target: true
  target_fitness: 1.0e-5
  stop_at_divergence: true
  divergence_fitness: 1.0e+12
  optim_params:
    x_init: 1
    init_sigma: 0.1
    popsize: 14
    dim: 30


---
name: "Holereacher_cmaes"
path: /media/gyh/sdb5/home/software/results/holereacher_cmaes/
params:
    name: 'holereacher_cmaes'
env_params:
  env_name: 'alr_envs:HoleReacher-v0'
  asyn_env:
    n_envs: 1
    hyperparams:
      n_samples: 14
      context: 'spawn'
      shared_memory: False,
      worker: _worker
    vectorizer: None
    base_seed: 0
  dmp_wrapper:
    num_dof: 5
    num_basis: 5
    duration: 2
    # dt=env._dt
    learn_goal: True,
    policy_type: "velocity"
    alpha_phase: 2
base_seed: 0
