ALRReacherSparseDMP-v0:
  name: ALRReacher + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 30
    sigma0: 1
    popsize: 10
    iteration: 800
    stop_criterion: opt < 3.2
  env_params:
    env_name: f'ALRReacherSparseDMP-v0'


ALRReacherBalanceSparseDMP-v0:
  name: ALRReacher + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 30
    sigma0: 1
    popsize: 10
    iteration: 800
    stop_criterion: opt < 3.2
  env_params:
    env_name: f'ALRReacherBalanceSparseDMP-v0'



DeepMindBallInCupDMP-v0:
  name: DeepMind_Ball_In_Cup + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 12
    sigma0: 1
    popsize: 10
    iteration: 300
    stop_criterion: opt < 3.2
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dmp-v0'

DeepMindBallInCupDenseDMP-v0:
  name: DeepMind_Ball_In_Cup + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 12
    sigma0: 1
    popsize: 10
    iteration: 300
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dense_dmp-v0'


DeepMindBallInCupProMP-v0:
  name: DeepMind_Ball_In_Cup + ProMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 10
    sigma0: 1
    popsize: 10
    iteration: 300
  env_params:
    env_name: f'dmc_ball_in_cup-catch_detpmp-v0'


DeepMindBallInCupDenseProMP-v0:
  name: DeepMind_Ball_In_Cup + ProMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 10
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dense_detpmp-v0'



DeepMindBallInCupDMP-v1:
  name: DeepMind_Ball_In_Cup + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 12
    sigma0: 1
    popsize: 10
    iteration: 200
    stop_criterion: opt < 3.2
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dmp-v1'


DeepMindBallInCupDenseDMP-v1:
  name: DeepMind_Ball_In_Cup + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 12
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dense_dmp-v1'

DeepMindBallInCupProMP-v1:
  name: DeepMind_Ball_In_Cup + ProMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 10
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_detpmp-v1'


DeepMindBallInCupDenseProMP-v1:
  name: DeepMind_Ball_In_Cup + ProMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 10
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dense_detpmp-v1'


DeepMindBallInCupDMP-v2:
  name: DeepMind_Ball_In_Cup + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 12
    sigma0: 1
    popsize: 10
    iteration: 200
    stop_criterion: opt < 3.2
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dmp-v2'


DeepMindBallInCupDenseDMP-v2:
  name: DeepMind_Ball_In_Cup + DMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 12
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dense_dmp-v2'


DeepMindBallInCupProMP-v2:
  name: DeepMind_Ball_In_Cup + ProMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 10
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_detpmp-v2'


DeepMindBallInCupDenseProMP-v2:
  name: DeepMind_Ball_In_Cup + ProMP
  algorithm: cmaes
  algo_params:
    x_init: 1
    dimension: 10
    sigma0: 1
    popsize: 10
    iteration: 200
  env_params:
    env_name: f'dmc_ball_in_cup-catch_dense_detpmp-v2'





