ALRBallInACupSimple-v0:
  name: Ball_In_A_Cup + PPO
  algorithm: ppo
  algo_params:
    batch_size: 50
    learning_rate: 0.0001
    n_steps: 2000
    total_timesteps: 5.e+7
    special_policy: CustomActorCriticPolicy
    special_callback: ALRBallInACupCallback
  env_params:
    env_name: alr_envs:ALRBallInACupSimpleDense-v0
    num_envs: 8
    wrapper: VecNormalize
    
    
DeepMindBallInCup-v0:
  name: DeepMind_Ball_In_Cup + PPO
  algorithm: ppo
  algo_params:
    batch_size: 50
    learning_rate: 0.0001
    n_steps: 2000
    total_timesteps: 2.e+6
    special_policy: MlpPolicy
  env_params:
    env_name: alr_envs:DeepMindBallInCupDense-v0
    num_envs: 8
    wrapper: VecNormalize


HoleReacher-v0:    
  name: DenseHoleReacher + PPO
  algorithm: ppo
  algo_params:
    batch_size: 50
    learning_rate: 0.0001
    n_steps: 2000
    total_timesteps: 2.e+6
    special_policy: MlpPolicy
  env_params:
    env_name: alr_envs:DenseHoleReacher-v0
    num_envs: 8
    wrapper: VecNormalize
