algo_params:
  batch_size: 200
  learning_rate: 0.0001
  n_steps: 20000
  num_timesteps: 10080000
  policy: MlpPolicy
  policy_kwargs:
    activation_fn: tanh
    pi: 256
    vf: 256
  policy_type: on_policy
  total_timesteps: 10000000.0
algorithm: ppo
env_params:
  env_name: alr_envs:ALRReacherBalance-v1
  num_envs: 8
  wrapper: VecNormalize
eval_env:
  eval_freq: 16384
  n_eval_episode: 1
path: logs/ppo/ALRReacherBalance-v1_1
path_in: logs/ppo/ALRReacherBalance-v1_1/PPO_1
path_out: logs/ppo/ALRReacherBalance-v1_1/data.csv
seed: 0
