algo_params:
  batch_size: 256
  learning_rate: 0.0001
  n_steps: 16384
  num_timesteps: 1000000
  policy: MlpPolicy
  special_callback: DMbicCallback
  total_timesteps: 1000000.0
algorithm: sac
env_params:
  env_name: alr_envs:DeepMindBallInCup-v0
  num_envs: 1
  wrapper: VecNormalize
eval_env:
  eval_freq: 500
  n_eval_episode: 10
name: DeepMind_Ball_In_Cup + SAC
path: logs/sac/DeepMindBallInCup-v0_5
path_in: logs/sac/DeepMindBallInCup-v0_5/SAC_1
path_out: logs/sac/DeepMindBallInCup-v0_5/data.csv
seed: 20
